export const products = [
  // ELECTRONICS
  {
    id: 1,
    slug: "airpods-pro-2",
    name: "AirPods Pro 2",
    price: 45,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "Bundle pricing: 1 for $45, 2 for $80, 5 for $150.",
  },
  {
    id: 2,
    slug: "airpods-pro-3",
    name: "AirPods Pro 3",
    price: 60,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "Bundle pricing: 1 for $60, 2 for $100, 5 for $200.",
  },
  {
    id: 3,
    slug: "airpods-max",
    name: "AirPods Max",
    price: 180,
    category: "Electronics",
    image: "/airpods-max.jpg",
    badge: "BEST SELLER",
    description: "AirPods Max. Bundle pricing: 2 for $160 each.",
  },
  {
    id: 4,
    slug: "apple-pencil-pro",
    name: "Apple Pencil Pro",
    price: 75,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "NEW DROP",
    description: "Apple Pencil Pro available for $75.",
  },
 
  // SHOES
  {
    id: 6,
    slug: "air-jordan-4",
    name: "Air Jordan 4",
    price: 100,
    category: "Shoes",
    image: "/nike-tech.jpg",
    badge: "BEST SELLER",
    description: "$100 without box. $120 with box. Multiple colorways available.",
  },
  {
    id: 7,
    slug: "air-jordan-5",
    name: "Air Jordan 5",
    price: 100,
    category: "Shoes",
    image: "/nike-tech.jpg",
    badge: "LIMITED STOCK",
    description: "$100 without box. $120 with box. Multiple colorways available.",
  },
  {
    id: 8,
    slug: "jordan-4-black-cat",
    name: "Jordan 4 Black Cat",
    price: 100,
    category: "Shoes",
    image: "/nike-tech.jpg",
    badge: "BEST SELLER",
    description: "$100 without box. $120 with box.",
  },
  {
    id: 9,
    slug: "jordan-4-military-black",
    name: "Jordan 4 Military Black",
    price: 100,
    category: "Shoes",
    image: "/nike-tech.jpg",
    badge: "NEW DROP",
    description: "$100 without box. $120 with box.",
  },
  {
    id: 10,
    slug: "jordan-4-white-cement",
    name: "Jordan 4 White Cement",
    price: 100,
    category: "Shoes",
    image: "/nike-tech.jpg",
    badge: "LIMITED STOCK",
    description: "$100 without box. $120 with box.",
  },

  // FRAGRANCES
  {
    id: 11,
    slug: "dior-sauvage",
    name: "Dior Sauvage",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "BEST SELLER",
    description: "Popular men’s fragrance.",
  },
  {
    id: 12,
    slug: "bleu-de-chanel",
    name: "Bleu De Chanel",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "BEST SELLER",
    description: "Premium designer fragrance.",
  },
  {
    id: 13,
    slug: "creed-aventus",
    name: "Creed Aventus",
    price: 60,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "NEW DROP",
    description: "High-demand premium fragrance.",
  },
  {
    id: 14,
    slug: "baccarat-rouge-540",
    name: "Baccarat Rouge 540",
    price: 60,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "LIMITED STOCK",
    description: "Premium fragrance option.",
  },
  {
    id: 15,
    slug: "lv-cologne",
    name: "LV Cologne",
    price: 80,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "BEST SELLER",
    description: "Premium Louis Vuitton fragrance.",
  },
  {
    id: 16,
    slug: "ysl-y",
    name: "YSL Y",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "NEW DROP",
    description: "Designer fragrance option.",
  },
  {
    id: 17,
    slug: "valentino-uomo",
    name: "Valentino Uomo",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "NEW DROP",
    description: "Popular designer fragrance.",
  },
  {
    id: 18,
    slug: "tom-ford-oud-wood",
    name: "Tom Ford Oud Wood",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "LIMITED STOCK",
    description: "Premium Tom Ford fragrance.",
  },
  {
    id: 19,
    slug: "prada-ocean",
    name: "Prada Ocean",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "NEW DROP",
    description: "Designer fragrance option.",
  },
  {
    id: 20,
    slug: "jpg-le-male",
    name: "JPG Le Male",
    price: 70,
    category: "Fragrances",
    image: "/hero-bg.png",
    badge: "BEST SELLER",
    description: "Popular Jean Paul Gaultier fragrance.",
  },

  // CLOTHING
  {
    id: 21,
    slug: "spider-hoodie",
    name: "Spider Hoodie",
    price: 70,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "BEST SELLER",
    description: "Spider hoodie. Premium quality.",
  },
  {
    id: 22,
    slug: "spider-sweatpants",
    name: "Spider Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "NEW DROP",
    description: "Spider sweatpants. Premium quality.",
  },
  {
    id: 23,
    slug: "essentials-hoodie-black",
    name: "Essentials Hoodie Black",
    price: 70,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "BEST SELLER",
    description: "Essentials hoodie in black.",
  },
  {
    id: 24,
    slug: "essentials-hoodie-beige",
    name: "Essentials Hoodie Beige",
    price: 70,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "NEW DROP",
    description: "Essentials hoodie in beige.",
  },
  {
    id: 25,
    slug: "essentials-sweatpants",
    name: "Essentials Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "LIMITED STOCK",
    description: "Essentials sweatpants.",
  },
  {
    id: 26,
    slug: "chrome-hearts-t-shirt",
    name: "Chrome Hearts T-Shirt",
    price: 60,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "BEST SELLER",
    description: "Chrome Hearts style t-shirt.",
  },
  {
    id: 27,
    slug: "chrome-hearts-long-sleeve",
    name: "Chrome Hearts Long Sleeve",
    price: 60,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "NEW DROP",
    description: "Chrome Hearts style long sleeve.",
  },
  {
    id: 28,
    slug: "chrome-hearts-shorts",
    name: "Chrome Hearts Shorts",
    price: 60,
    category: "Clothing",
    image: "/nike-tech.jpg",
    badge: "LIMITED STOCK",
    description: "Chrome Hearts style shorts.",
  },

  // BAGS - MESSAGE FOR PRICING
  {
    id: 29,
    slug: "lv-neverfull",
    name: "LV Neverfull",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 30,
    slug: "lv-onthego",
    name: "LV OnTheGo",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 31,
    slug: "lv-speedy",
    name: "LV Speedy",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 32,
    slug: "chanel-classic-flap",
    name: "Chanel Classic Flap",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 33,
    slug: "chanel-22",
    name: "Chanel 22",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 34,
    slug: "dior-book-tote",
    name: "Dior Book Tote",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 35,
    slug: "dior-saddle-bag",
    name: "Dior Saddle Bag",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 36,
    slug: "prada-re-edition-2005",
    name: "Prada Re-Edition 2005",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 37,
    slug: "ysl-loulou",
    name: "YSL LouLou",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 38,
    slug: "ysl-sunset",
    name: "YSL Sunset",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 39,
    slug: "goyard-saint-louis",
    name: "Goyard Saint Louis",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
  {
    id: 40,
    slug: "bottega-andiamo",
    name: "Bottega Andiamo",
    price: 0,
    category: "Bags",
    image: "/hero-bg.png",
    badge: "MESSAGE FOR PRICING",
    description: "Custom factory bag. Message us on Telegram for pricing.",
  },
];