export const products = [
  // ELECTRONICS
  {
    id: 1,
    slug: "airpods-pro-2",
    name: "AirPods Pro 2",
    price: 45,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "Bundle pricing: 1 for $45, 2 for $80, 5 for $150.",
    deals: [
  { quantity: 1, price: 45 },
  { quantity: 2, price: 80 },
  { quantity: 5, price: 150 },
],
  },
  {
    id: 2,
    slug: "airpods-pro-3",
    name: "AirPods Pro 3",
    price: 60,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "Bundle pricing: 1 for $60, 2 for $100, 5 for $200.",
   deals: [
  { quantity: 1, price: 60 },
  { quantity: 2, price: 100 },
  { quantity: 5, price: 200 },
],
  },
  {
    id: 3,
    slug: "airpods-max",
    name: "AirPods Max",
    price: 160,
    category: "Electronics",
    image: "/airpods-max.jpg",
    badge: "BEST SELLER",
    description: "AirPods Max. Bundle pricing: 2 for $160 each.",
    deals: [
  { quantity: 1, price: 160
   },
  { quantity: 2, price: 280 },
  { quantity: 5, price: 650 },
],
  },
  {
    id: 4,
    slug: "airpods-gen-4",
    name: "AirPods Gen 4",
    price: 35,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "Bundle pricing: 1 for $35, 2 for $55, 5 for $125.",
    deals: [
  { quantity: 1, price: 35 },
  { quantity: 2, price: 55 },
  { quantity: 5, price: 125 },
],
  },
  {
  id: 5, // Change this to the next unused ID
  slug: "beats-solo-4",
  name: "Beats Solo 4",
  price: 65,
  category: "Electronics",
  image: "/beatssolo4.png",
  badge: "BUNDLE DEAL",
  description: "Premium wireless headphones with bundle pricing.",
  deals: [
    { quantity: 1, price: 60 },
    { quantity: 2, price: 110 },
    { quantity: 5, price: 250 },
  ],
},

  // SHOES\
// SHOES

{
  id: 7,
  slug: "jordan-4-black-cat",
  name: "Jordan 4 Black Cat",
  price: 100,
  category: "Shoes",
  image: "/air-jordan-4-black-cat.png",
  badge: "BEST SELLER",
  description: "$100 without box. $120 with box.",
  deals: [
  { quantity: 1, price: 100 },
  { quantity: 2, price: 190 },
  { quantity: 5, price: 450 },
],
},

{
  id: 8,
  slug: "jordan-4-military-black",
  name: "Jordan 4 Military Black",
  price: 100,
  category: "Shoes",
  image: "/air-jordan-4-military-black.png",
  badge: "BEST SELLER",
  description: "$100 without box. $120 with box.",
  deals: [
  { quantity: 1, price: 100 },
  { quantity: 2, price: 190 },
  { quantity: 5, price: 450 },
],
},

{
  id: 9,
  slug: "jordan-4-white-cement",
  name: "Jordan 4 White Cement",
  price: 100,
  category: "Shoes",
  image: "/air-jordan-4-white-cement.png",
  badge: "LIMITED STOCK",
  description: "$100 without box. $120 with box.",
  deals: [
  { quantity: 1, price: 100 },
  { quantity: 2, price: 190 },
  { quantity: 5, price: 450 },
],
},

  // FRAGRANCES
// FRAGRANCES
{
  id: 10, // Use the next available unique ID
  slug: "parfums-de-marly",
  name: "Parfums de Marly",
  price: 70,
  category: "Fragrances",
  image: "/parfums-de-marly.jpg",
  badge: "NEW",
  description: "Luxury niche fragrance with exceptional performance and premium quality.",
  deals: [
    { quantity: 1, price: 70 },
    { quantity: 2, price: 130 },
    { quantity: 5, price: 300 },
    { quantity: 10, price: 550 },
  ],
},
{
  id: 11,
  slug: "dior-sauvage",
  name: "Dior Sauvage",
  price: 50,
  category: "Fragrances",
  image: "/dior-sauvage.jpg",
  badge: "BEST SELLER",
  description: "One of the most popular men's fragrances worldwide.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},
{
  id: 12,
  slug: "bleu-de-chanel",
  name: "Bleu De Chanel",
  price: 50,
  category: "Fragrances",
  image: "/bleu-de-chanel.jpg",
  badge: "BEST SELLER",
  description: "Fresh, clean and versatile fragrance.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 13,
  slug: "creed-aventus",
  name: "Creed Aventus",
  price: 50,
  category: "Fragrances",
  image: "/creed-aventus.jpg",
  badge: "LUXURY",
  description: "Luxury fragrance with a powerful signature scent.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 14,
  slug: "baccarat-rouge-540",
  name: "Baccarat Rouge 540",
  price: 50,
  category: "Fragrances",
  image: "/baccarat-rouge-540.jpg",
  badge: "BEST SELLER",
  description: "Iconic luxury fragrance with outstanding projection.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 15,
  slug: "lv-cologne",
  name: "Louis Vuitton Cologne",
  price: 80,
  category: "Fragrances",
  image: "/lv-cologne.jpg",
  badge: "LUXURY",
  description: "Premium Louis Vuitton fragrance collection.",
  deals: [
  { quantity: 1, price: 80 },
  { quantity: 5, price: 400 },
  { quantity: 10, price: 800 },
],
},

{
  id: 16,
  slug: "ysl-y",
  name: "YSL Y",
  price: 50,
  category: "Fragrances",
  image: "/ysl-y.jpg",
  badge: "POPULAR",
  description: "Fresh and modern Yves Saint Laurent fragrance.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 17,
  slug: "valentino-uomo",
  name: "Valentino Uomo",
  price: 50,
  category: "Fragrances",
  image: "/valentino-uomo.jpg",
  badge: "NEW DROP",
  description: "Elegant Valentino fragrance with premium notes.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 18,
  slug: "tom-ford-oud-wood",
  name: "Tom Ford Oud Wood",
  price: 50,
  category: "Fragrances",
  image: "/tom-ford-oud-wood.jpg",
  badge: "LUXURY",
  description: "Sophisticated Tom Ford fragrance.",
  deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},

{
  id: 19,
  slug: "jean-paul-gaultier-le-male",
  name: "Jean Paul Gaultier Le Male",
  price: 50,
  category: "Fragrances",
  image: "/jean-paul-gaultier-le-male.jpg",
  badge: "BEST SELLER",
  description: "Popular Jean Paul Gaultier fragrance.",
 deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},
{
  id: 20, // use the next available ID
  slug: "ysl-libre",
  name: "YSL Libre",
  price: 50,
  category: "Fragrances",
  image: "/ysl-libre.jpg",
  description: "Elegant floral fragrance with a modern and luxurious scent.",
  deals: [
  { quantity: 1, price: 50 },
  { quantity: 2, price: 90 },
  { quantity: 5, price: 200 },
  { quantity: 10, price: 350 },
],
},
// CLOTHING

{
  id: 21,
  slug: "spider-hoodie",
  name: "Spider Hoodie",
  price: 70,
  category: "Clothing",
  image: "/spider-hoodie.png",
  badge: "BEST SELLER",
  description: "Spider hoodie. Premium quality.",
  deals: [
  { quantity: 1, price: 70 },
  { quantity: 2, price: 130 },
  { quantity: 5, price: 300 },
],
},

{
  id: 22,
  slug: "spider-sweatpants",
  name: "Spider Sweatpants",
  price: 70,
  category: "Clothing",
  image: "/spider-sweatpants.png",
  badge: "NEW DROP",
  description: "Spider sweatpants. Premium quality.",
  deals: [
  { quantity: 1, price: 70 },
  { quantity: 2, price: 130 },
  { quantity: 5, price: 300 },
],
},

{
  id: 23,
  slug: "essentials-hoodie-beige",
  name: "Essentials Hoodie Beige",
  price: 70,
  category: "Clothing",
  image: "/essentials-hoodie-beige.png",
  badge: "BEST SELLER",
  description: "Essentials beige hoodie. Premium quality.",
  deals: [
  { quantity: 1, price: 70 },
  { quantity: 2, price: 130 },
  { quantity: 5, price: 300 },
],
},

{
  id: 24,
  slug: "essentials-sweatpants-black",
  name: "Essentials Sweatpants Black",
  price: 70,
  category: "Clothing",
  image: "/essentials-sweatpants.png",
  badge: "LIMITED STOCK",
  description: "Essentials black sweatpants. Premium quality.",
  deals: [
  { quantity: 1, price: 70 },
  { quantity: 2, price: 130 },
  { quantity: 5, price: 300 },
],
},

{
  id: 25,
  slug: "chrome-hearts-t-hirt",
  name: "Chrome Hearts T-Shirt",
  price: 60,
  category: "Clothing",
  image: "/chrome-hearts-tshirt.png",
  badge: "BEST SELLER",
  description: "Chrome Hearts style t-shirt.",
  deals: [
  { quantity: 1, price: 60 },
  { quantity: 2, price: 110 },
  { quantity: 5, price: 250 },
],
},

{
  id: 26,
  slug: "chrome-hearts-long-sleeve",
  name: "Chrome Hearts Long Sleeve",
  price: 60,
  category: "Clothing",
  image: "/chrome-hearts-long-sleeve.png",
  badge: "NEW DROP",
  description: "Chrome Hearts style long sleeve.",
  deals: [
  { quantity: 1, price: 60 },
  { quantity: 2, price: 110 },
  { quantity: 5, price: 250 },
],
},

  // BAGS - MESSAGE FOR PRICING
 // BAGS

{
  id: 29,
  slug: "lv-neverfull",
  name: "LV Neverfull",
  price: 0,
  category: "Bags",
  image: "/lv-neverfull.png",
  badge: "BEST SELLER",
  description: "Message for pricing and available options.",
},

{
  id: 30,
  slug: "lv-onthego",
  name: "LV OnTheGo",
  price: 0,
  category: "Bags",
  image: "/lv-onthego.png",
  badge: "NEW DROP",
  description: "Message for pricing and available options.",
},

{
  id: 31,
  slug: "lv-speedy",
  name: "LV Speedy",
  price: 0,
  category: "Bags",
  image: "/lv-speedy.png",
  badge: "BEST SELLER",
  description: "Message for pricing and available options.",
},

{
  id: 32,
  slug: "lv-pochette-metis",
  name: "LV Pochette Metis",
  price: 0,
  category: "Bags",
  image: "/lv-pochette-metis.png",
  badge: "LIMITED STOCK",
  description: "Message for pricing and available options.",
},

{
  id: 33,
  slug: "ysl-loulou",
  name: "YSL LouLou",
  price: 0,
  category: "Bags",
  image: "/ysl-loulou.png",
  badge: "BEST SELLER",
  description: "Message for pricing and available options.",
},

{
  id: 34,
  slug: "ysl-sunset",
  name: "YSL Sunset",
  price: 0,
  category: "Bags",
  image: "/ysl-sunset.png",
  badge: "NEW DROP",
  description: "Message for pricing and available options.",
},

{
  id: 35,
  slug: "chanel-classic-flap",
  name: "Chanel Classic Flap",
  price: 0,
  category: "Bags",
  image: "/chanel-classic-flap.png",
  badge: "LIMITED STOCK",
  description: "Message for pricing and available options.",
},
]
