export const products = [
  // ELECTRONICS

  {
    id: 1,
    slug: "airpods-pro-2",
    name: "AirPods Pro 2",
    price: 40,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "AirPods Pro 2.",
    deals: [
      { quantity: 1, price: 40 },
      { quantity: 2, price: 76 },
      { quantity: 5, price: 175 },
      { quantity: 10, price: 300 },
    ],
  },

  {
    id: 2,
    slug: "airpods-pro-3",
    name: "AirPods Pro 3",
    price: 45,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "AirPods Pro 3.",
    deals: [
      { quantity: 1, price: 45 },
      { quantity: 2, price: 80 },
      { quantity: 5, price: 190 },
      { quantity: 10, price: 350 },
    ],
  },

  {
    id: 3,
    slug: "airpods-max",
    name: "AirPods Max",
    price: 160,
    category: "Electronics",
    image: "/airpods-max.jpg",
    badge: "BEST SELLER",
    description: "AirPods Max.",
    deals: [
      { quantity: 1, price: 160 },
      { quantity: 2, price: 280 },
      { quantity: 5, price: 650 },
    ],
  },

  {
    id: 4,
    slug: "airpods-gen-4",
    name: "AirPods Gen 4",
    price: 35,
    category: "Electronics",
    image: "/airpods-pro.jpg",
    badge: "BUNDLE DEAL",
    description: "AirPods Gen 4.",
    deals: [
      { quantity: 1, price: 35 },
      { quantity: 2, price: 60 },
      { quantity: 5, price: 140 },
      { quantity: 10, price: 250 },
    ],
  },

  {
    id: 5,
    slug: "beats-solo-4",
    name: "Beats Solo 4",
    price: 65,
    category: "Electronics",
    image: "/beatssolo4.png",
    badge: "BUNDLE DEAL",
    description: "Premium wireless headphones with bundle pricing.",
    deals: [
      { quantity: 1, price: 60 },
      { quantity: 2, price: 110 },
      { quantity: 5, price: 250 },
    ],
  },

  // FRAGRANCES

  {
    id: 10,
    slug: "parfums-de-marly",
    name: "Parfums de Marly",
    price: 70,
    category: "Fragrances",
    image: "/parfums-de-marly.jpg",
    badge: "NEW",
    description:
      "Luxury niche fragrance with exceptional performance and premium quality.",
    deals: [
      { quantity: 1, price: 70 },
      { quantity: 2, price: 130 },
      { quantity: 5, price: 300 },
      { quantity: 10, price: 550 },
    ],
  },

  {
    id: 11,
    slug: "dior-sauvage",
    name: "Dior Sauvage",
    price: 50,
    category: "Fragrances",
    image: "/dior-sauvage.jpg",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 12,
    slug: "creed-aventus",
    name: "Creed Aventus",
    price: 50,
    category: "Fragrances",
    image: "/creed-aventus.jpg",
    description: "Premium designer fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 13,
    slug: "baccarat-rouge-540",
    name: "Baccarat Rouge 540",
    price: 50,
    category: "Fragrances",
    image: "/baccarat-rouge-540.jpg",
    description: "Premium designer fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 14,
    slug: "lv-cologne",
    name: "Louis Vuitton Cologne",
    price: 80,
    category: "Fragrances",
    image: "/lv-cologne.jpg",
    badge: "LUXURY",
    description: "Premium Louis Vuitton fragrance collection.",
    deals: [
      { quantity: 1, price: 80 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 15,
    slug: "ysl-y",
    name: "YSL Y",
    price: 50,
    category: "Fragrances",
    image: "/ysl-y.jpg",
    description: "Fresh and modern Yves Saint Laurent fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 16,
    slug: "valentino-uomo",
    name: "Valentino Uomo",
    price: 50,
    category: "Fragrances",
    image: "/valentino-uomo.jpg",
    description: "Premium designer fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 17,
    slug: "tom-ford-oud-wood",
    name: "Tom Ford Oud Wood",
    price: 50,
    category: "Fragrances",
    image: "/tom-ford-oud-wood.jpg",
    description: "Premium Tom Ford fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 18,
    slug: "jean-paul-gaultier-le-male",
    name: "Jean Paul Gaultier Le Male",
    price: 50,
    category: "Fragrances",
    image: "/jean-paul-gaultier-le-male.jpg",
    description: "Popular Jean Paul Gaultier fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 19,
    slug: "ysl-libre",
    name: "YSL Libre",
    price: 50,
    category: "Fragrances",
    image: "/ysl-libre.jpg",
    description: "Elegant floral fragrance with a modern and luxurious scent.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 20,
    slug: "jean-paul-gaultier-le-beau-le-parfum",
    name: "Jean Paul Gaultier Le Beau Le Parfum",
    price: 50,
    category: "Fragrances",
    image: "/jpg-le-beau-le-parfum.jpg",
    description: "Popular Jean Paul Gaultier fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 21,
    slug: "jean-paul-gaultier-le-male-elixir",
    name: "Jean Paul Gaultier Le Male Elixir",
    price: 50,
    category: "Fragrances",
    image: "/jpg-le-male-elixir.jpg",
    badge: "POPULAR",
    description: "Premium Jean Paul Gaultier fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 22,
    slug: "creed-absolute",
    name: "Creed Absolute",
    price: 70,
    category: "Fragrances",
    image: "/Creed-Absolute.png",
    description:
      "A bold and sophisticated fragrance with a rich, fresh scent made to leave a lasting impression.",
    deals: [
      { quantity: 1, price: 70 },
      { quantity: 2, price: 120 },
      { quantity: 5, price: 250 },
      { quantity: 10, price: 400 },
    ],
  },

  {
    id: 23,
    slug: "santal-33",
    name: "Santal 33",
    price: 50,
    category: "Fragrances",
    image: "/santal-33.jpg",
    description: "New Drop",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 24,
    slug: "armani-stronger-with-you-intensely",
    name: "Armani Stronger With You Intensely",
    price: 50,
    category: "Fragrances",
    image: "/armani-stronger-with-you-intensely.png",
    badge: "POPULAR",
    description:
      "Popular Armani fragrance with a warm, sweet and long-lasting scent.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 25,
    slug: "bleu-de-chanel",
    name: "Bleu de Chanel",
    price: 50,
    category: "Fragrances",
    image: "/bleu-de-chanel.jpg",
    badge: "POPULAR",
    description: "Fresh, clean and versatile Chanel fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 26,
    slug: "azzaro-the-most-wanted",
    name: "Azzaro The Most Wanted",
    price: 50,
    category: "Fragrances",
    image: "/azzaro-the-most-wanted.png",
    badge: "POPULAR",
    description: "Bold and sweet men's fragrance with strong performance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 27,
    slug: "club-de-nuit-intense-man",
    name: "Club de Nuit Intense Man",
    price: 50,
    category: "Fragrances",
    image: "/club-de-nuit-intense-man.png",
    description: "Popular fresh and masculine fragrance from Armaf.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 28,
    slug: "ysl-myslf",
    name: "YSL MYSLF",
    price: 50,
    category: "Fragrances",
    image: "/ysl-myslf.png",
    badge: "POPULAR",
    description:
      "Modern Yves Saint Laurent fragrance with a clean and fresh scent.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 29,
    slug: "tom-ford-tobacco-vanille",
    name: "Tom Ford Tobacco Vanille",
    price: 50,
    category: "Fragrances",
    image: "/tom-ford-tobacco-vanille.png",
    badge: "LUXURY",
    description:
      "Rich Tom Ford fragrance with warm tobacco and vanilla notes.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 30,
    slug: "armani-acqua-di-gio",
    name: "Armani Acqua di Giò",
    price: 50,
    category: "Fragrances",
    image: "/armani-acqua-di-gio.png",
    description: "Classic fresh and aquatic Giorgio Armani fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 31,
    slug: "versace-eros",
    name: "Versace Eros",
    price: 50,
    category: "Fragrances",
    image: "/versace-eros.png",
    badge: "POPULAR",
    description: "Fresh, sweet and bold Versace fragrance for men.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 32,
    slug: "carolina-herrera-good-girl",
    name: "Carolina Herrera Good Girl",
    price: 50,
    category: "Fragrances",
    image: "/carolina-herrera-good-girl.png",
    badge: "POPULAR",
    description:
      "Popular women's fragrance with a sweet and sophisticated scent.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 33,
    slug: "burberry-her",
    name: "Burberry Her",
    price: 50,
    category: "Fragrances",
    image: "/burberry-her.png",
    badge: "POPULAR",
    description: "Sweet and fruity Burberry fragrance for women.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 34,
    slug: "ysl-black-opium",
    name: "YSL Black Opium",
    price: 50,
    category: "Fragrances",
    image: "/ysl-black-opium.png",
    badge: "BEST SELLER",
    description: "Iconic sweet and warm Yves Saint Laurent fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 35,
    slug: "prada-paradoxe",
    name: "Prada Paradoxe",
    price: 50,
    category: "Fragrances",
    image: "/prada-paradoxe.png",
    badge: "POPULAR",
    description: "Modern floral and sweet Prada fragrance for women.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 36,
    slug: "lancome-la-vie-est-belle",
    name: "Lancôme La Vie Est Belle",
    price: 50,
    category: "Fragrances",
    image: "/lancome-la-vie-est-belle.png",
    description: "Popular sweet and elegant Lancôme fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 37,
    slug: "chanel-coco-mademoiselle",
    name: "Chanel Coco Mademoiselle",
    price: 50,
    category: "Fragrances",
    image: "/chanel-coco-mademoiselle.png",
    badge: "POPULAR",
    description: "Classic Chanel fragrance with a fresh and elegant scent.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  {
    id: 38,
    slug: "dolce-gabbana-light-blue",
    name: "Dolce & Gabbana Light Blue",
    price: 50,
    category: "Fragrances",
    image: "/dolce-gabbana-light-blue.png",
    description: "Fresh citrus and aquatic Dolce & Gabbana fragrance.",
    deals: [
      { quantity: 1, price: 50 },
      { quantity: 2, price: 96 },
      { quantity: 5, price: 225 },
      { quantity: 10, price: 420 },
    ],
  },

  // SHOES

  {
    id: 100,
    slug: "air-jordan-4-a-ma-maniere",
    name: "Air Jordan 4 A Ma Maniére",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-a-ma-maniere.png",
    deals: [],
  },

  {
    id: 101,
    slug: "air-jordan-4-black-cat",
    name: "Air Jordan 4 Black Cat",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-black-cat.png",
    deals: [],
  },

  {
    id: 102,
    slug: "air-jordan-4-black-cement-bred",
    name: "Air Jordan 4 Black Cement Bred",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-black-cement-bred.png",
    deals: [],
  },

  {
    id: 103,
    slug: "air-jordan-4-brick-by-brick",
    name: "Air Jordan 4 Brick By Brick",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-brick-by-brick.png",
    deals: [],
  },

  {
    id: 104,
    slug: "air-jordan-4-cave-stone",
    name: "Air Jordan 4 Cave Stone",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-cave-stone.png",
    deals: [],
  },

  {
    id: 105,
    slug: "air-jordan-4-cool-grey",
    name: "Air Jordan 4 Cool Grey",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-cool-grey.png",
    deals: [],
  },

  {
    id: 106,
    slug: "air-jordan-4-fire-red",
    name: "Air Jordan 4 Fire Red",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-fire-red.png",
    deals: [],
  },

  {
    id: 107,
    slug: "air-jordan-4-iced-carmine",
    name: "Air Jordan 4 Iced Carmine",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-iced-carmine.png",
    deals: [],
  },

  {
    id: 108,
    slug: "air-jordan-4-infrared",
    name: "Air Jordan 4 Infrared",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-infrared.png",
    deals: [],
  },

  {
    id: 109,
    slug: "air-jordan-4-kaws",
    name: "Air Jordan 4 KAWS",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-kaws.png",
    deals: [],
  },

  {
    id: 110,
    slug: "air-jordan-4-lightning",
    name: "Air Jordan 4 Lightning",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-lightning.png",
    deals: [],
  },

  {
    id: 111,
    slug: "air-jordan-4-metallic-green",
    name: "Air Jordan 4 Metallic Green",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-metallic-green.png",
    deals: [],
  },

  {
    id: 112,
    slug: "air-jordan-4-metallic-purple",
    name: "Air Jordan 4 Metallic Purple",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-metallic-purple.png",
    deals: [],
  },

  {
    id: 113,
    slug: "air-jordan-4-metallic-red",
    name: "Air Jordan 4 Metallic Red",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-metallic-red.png",
    deals: [],
  },

  {
    id: 114,
    slug: "air-jordan-4-midnight-navy",
    name: "Air Jordan 4 Midnight Navy",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-midnight-navy.png",
    deals: [],
  },

  {
    id: 115,
    slug: "air-jordan-4-military-black",
    name: "Air Jordan 4 Military Black",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-military-black.png",
    deals: [],
  },

  {
    id: 116,
    slug: "air-jordan-4-military-blue",
    name: "Air Jordan 4 Military Blue",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-military-blue.png",
    deals: [],
  },

  {
    id: 117,
    slug: "air-jordan-4-off-white-sail",
    name: "Air Jordan 4 Off-White Sail",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-off-white-sail.png",
    deals: [],
  },

  {
    id: 118,
    slug: "air-jordan-4-pure-money",
    name: "Air Jordan 4 Pure Money",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-pure-money.png",
    deals: [],
  },

  {
    id: 119,
    slug: "air-jordan-4-red-thunder",
    name: "Air Jordan 4 Red Thunder",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-red-thunder.png",
    deals: [],
  },

  {
    id: 120,
    slug: "air-jordan-4-reimagined-white-cement",
    name: "Air Jordan 4 Reimagined White Cement",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-reimagined-white-cement.png",
    deals: [],
  },

  {
    id: 121,
    slug: "air-jordan-4-seafoam",
    name: "Air Jordan 4 Seafoam",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-seafoam.png",
    deals: [],
  },

  {
    id: 122,
    slug: "air-jordan-4-taupe-haze",
    name: "Air Jordan 4 Taupe Haze",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-taupe-haze.png",
    deals: [],
  },

  {
    id: 123,
    slug: "air-jordan-4-thunder",
    name: "Air Jordan 4 Thunder",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-thunder.png",
    deals: [],
  },

  {
    id: 124,
    slug: "air-jordan-4-travis-scott-cactus-jack",
    name: "Air Jordan 4 Travis Scott Cactus Jack",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-travis-scott-cactus-jack.png",
    deals: [],
  },

  {
    id: 125,
    slug: "air-jordan-4-undefeated",
    name: "Air Jordan 4 Undefeated",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-undefeated.png",
    deals: [],
  },

  {
    id: 126,
    slug: "air-jordan-4-university-blue",
    name: "Air Jordan 4 University Blue",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-university-blue.png",
    deals: [],
  },

  {
    id: 127,
    slug: "air-jordan-4-vivid-sulfur",
    name: "Air Jordan 4 Vivid Sulfur",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-vivid-sulfur.png",
    deals: [],
  },

  {
    id: 128,
    slug: "air-jordan-4-white-cement",
    name: "Air Jordan 4 White Cement",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-4-white-cement.png",
    deals: [],
  },

  {
    id: 129,
    slug: "air-jordan-5-anthracite",
    name: "Air Jordan 5 Anthracite",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-anthracite.png",
    deals: [],
  },

  {
    id: 130,
    slug: "air-jordan-5-aqua",
    name: "Air Jordan 5 Aqua",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-aqua.png",
    deals: [],
  },

  {
    id: 131,
    slug: "air-jordan-5-bel-air",
    name: "Air Jordan 5 Bel Air",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-bel-air.png",
    deals: [],
  },

  {
    id: 132,
    slug: "air-jordan-5-black-grape",
    name: "Air Jordan 5 Black Grape",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-black-grape.png",
    deals: [],
  },

  {
    id: 133,
    slug: "air-jordan-5-black-metallic",
    name: "Air Jordan 5 Black Metallic",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-black-metallic.png",
    deals: [],
  },

  {
    id: 134,
    slug: "air-jordan-5-black-racer-blue",
    name: "Air Jordan 5 Black Racer Blue",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-black-racer-blue.png",
    deals: [],
  },

  {
    id: 135,
    slug: "air-jordan-5-burgundy",
    name: "Air Jordan 5 Burgundy",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-burgundy.png",
    deals: [],
  },

  {
    id: 136,
    slug: "air-jordan-5-concord",
    name: "Air Jordan 5 Concord",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-concord.png",
    deals: [],
  },

  {
    id: 137,
    slug: "air-jordan-5-cool-grey",
    name: "Air Jordan 5 Cool Grey",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-cool-grey.png",
    deals: [],
  },

  {
    id: 138,
    slug: "air-jordan-5-fire-red",
    name: "Air Jordan 5 Fire Red",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-fire-red.png",
    deals: [],
  },

  {
    id: 139,
    slug: "air-jordan-5-gore-tex-off-noir",
    name: "Air Jordan 5 Gore-Tex Off Noir",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-gore-tex-off-noir.png",
    deals: [],
  },

  {
    id: 140,
    slug: "air-jordan-5-grape",
    name: "Air Jordan 5 Grape",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-grape.png",
    deals: [],
  },

  {
    id: 141,
    slug: "air-jordan-5-green-bean",
    name: "Air Jordan 5 Green Bean",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-green-bean.png",
    deals: [],
  },

  {
    id: 142,
    slug: "air-jordan-5-laney",
    name: "Air Jordan 5 Laney",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-laney.png",
    deals: [],
  },

  {
    id: 143,
    slug: "air-jordan-5-metallic-silver",
    name: "Air Jordan 5 Metallic Silver",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-metallic-silver.png",
    deals: [],
  },

  {
    id: 144,
    slug: "air-jordan-5-michigan",
    name: "Air Jordan 5 Michigan",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-michigan.png",
    deals: [],
  },

  {
    id: 145,
    slug: "air-jordan-5-midnight-navy",
    name: "Air Jordan 5 Midnight Navy",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-midnight-navy.png",
    deals: [],
  },

  {
    id: 146,
    slug: "air-jordan-5-moonlight",
    name: "Air Jordan 5 Moonlight",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-moonlight.png",
    deals: [],
  },

  {
    id: 147,
    slug: "air-jordan-5-off-white",
    name: "Air Jordan 5 Off-White",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-off-white.png",
    deals: [],
  },

  {
    id: 148,
    slug: "air-jordan-5-oreo",
    name: "Air Jordan 5 Oreo",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-oreo.png",
    deals: [],
  },

  {
    id: 149,
    slug: "air-jordan-5-psg",
    name: "Air Jordan 5 PSG",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-psg.png",
    deals: [],
  },

  {
    id: 150,
    slug: "air-jordan-5-raging-bull",
    name: "Air Jordan 5 Raging Bull",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-raging-bull.png",
    deals: [],
  },

  {
    id: 151,
    slug: "air-jordan-5-seoul",
    name: "Air Jordan 5 Seoul",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-seoul.png",
    deals: [],
  },

  {
    id: 152,
    slug: "air-jordan-5-supreme",
    name: "Air Jordan 5 Supreme",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-supreme.png",
    deals: [],
  },

  {
    id: 153,
    slug: "air-jordan-5-top-3",
    name: "Air Jordan 5 Top 3",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-top-3.png",
    deals: [],
  },

  {
    id: 154,
    slug: "air-jordan-5-toro-bravo",
    name: "Air Jordan 5 Toro Bravo",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-toro-bravo.png",
    deals: [],
  },

  {
    id: 155,
    slug: "air-jordan-5-unc",
    name: "Air Jordan 5 UNC",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-unc.png",
    deals: [],
  },

  {
    id: 156,
    slug: "air-jordan-5-white-black",
    name: "Air Jordan 5 White Black",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-white-black.png",
    deals: [],
  },

  {
    id: 157,
    slug: "air-jordan-5-white-cement",
    name: "Air Jordan 5 White Cement",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-white-cement.png",
    deals: [],
  },

  {
    id: 158,
    slug: "air-jordan-5-wings",
    name: "Air Jordan 5 Wings",
    price: 100,
    withBoxPrice: 120,
    category: "Shoes",
    image: "/shoe/air-jordan-5-wings.png",
    deals: [],
  },

  // SELECTED CLOTHING ONLY

  {
    id: 500,
    slug: "chrome-hearts-black-logo-long-sleeve",
    name: "Chrome Hearts Black Logo Long Sleeve",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-black-logo-long-sleeve.png",
    deals: [],
  },

  {
    id: 501,
    slug: "chrome-hearts-black-long-sleeve",
    name: "Chrome Hearts Black Long Sleeve",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-black-long-sleeve.png",
    deals: [],
  },

  {
    id: 502,
    slug: "chrome-hearts-black-pink-long-sleeve",
    name: "Chrome Hearts Black Pink Long Sleeve",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-black-pink-long-sleeve.png",
    deals: [],
  },

  {
    id: 503,
    slug: "chrome-hearts-black-tshirt",
    name: "Chrome Hearts Black T-Shirt",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-black-tshirt.png",
    deals: [],
  },

  {
    id: 504,
    slug: "chrome-hearts-white-black-raglan",
    name: "Chrome Hearts White Black Raglan",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-white-black-raglan.png",
    deals: [],
  },

  {
    id: 505,
    slug: "chrome-hearts-white-blue-raglan",
    name: "Chrome Hearts White Blue Raglan",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-white-blue-raglan.png",
    deals: [],
  },

  {
    id: 506,
    slug: "chrome-hearts-white-rainbow-long-sleeve",
    name: "Chrome Hearts White Rainbow Long Sleeve",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/chrome-hearts-white-rainbow-long-sleeve.png",
    deals: [],
  },

  {
    id: 507,
    slug: "essentials-black-logo-shorts",
    name: "Essentials Black Logo Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/essentials-black-logo-shorts.png",
    deals: [],
  },

  {
    id: 508,
    slug: "essentials-black-shorts",
    name: "Essentials Black Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/essentials-black-shorts.png",
    deals: [],
  },

  {
    id: 509,
    slug: "essentials-black-sweatpants",
    name: "Essentials Black Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-black-sweatpants.png",
    deals: [],
  },

  {
    id: 510,
    slug: "essentials-coral-shorts",
    name: "Essentials Coral Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/essentials-coral-shorts.png",
    deals: [],
  },

  {
    id: 511,
    slug: "essentials-cream-logo-hoodie",
    name: "Essentials Cream Logo Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-cream-logo-hoodie.png",
    deals: [],
  },

  {
    id: 512,
    slug: "essentials-cream-sweatpants",
    name: "Essentials Cream Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-cream-sweatpants.png",
    deals: [],
  },

  {
    id: 513,
    slug: "essentials-grey-minimal-hoodie",
    name: "Essentials Grey Minimal Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-grey-minimal-hoodie.png",
    deals: [],
  },

  {
    id: 514,
    slug: "essentials-grey-shorts",
    name: "Essentials Grey Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/essentials-grey-shorts.png",
    deals: [],
  },

  {
    id: 515,
    slug: "essentials-grey-sweatpants",
    name: "Essentials Grey Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-grey-sweatpants.png",
    deals: [],
  },

  {
    id: 516,
    slug: "essentials-red-fear-of-god-hoodie",
    name: "Essentials Red Fear of God Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-red-fear-of-god-hoodie.png",
    deals: [],
  },

  {
    id: 517,
    slug: "essentials-red-sweatpants",
    name: "Essentials Red Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-red-sweatpants.png",
    deals: [],
  },

  {
    id: 518,
    slug: "essentials-taupe-minimal-hoodie",
    name: "Essentials Taupe Minimal Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-taupe-minimal-hoodie.png",
    deals: [],
  },

  {
    id: 519,
    slug: "essentials-taupe-sweatpants",
    name: "Essentials Taupe Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/essentials-taupe-sweatpants.png",
    deals: [],
  },

  {
    id: 520,
    slug: "essentials-white-grey-shorts",
    name: "Essentials White Grey Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/essentials-white-grey-shorts.png",
    deals: [],
  },

  {
    id: 521,
    slug: "sp5der-atlanta-navy-hoodie",
    name: "SP5DER Atlanta Navy Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-atlanta-navy-hoodie.png",
    deals: [],
  },

  {
    id: 522,
    slug: "sp5der-atlanta-navy-sweatpants",
    name: "SP5DER Atlanta Navy Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-atlanta-navy-sweatpants.png",
    deals: [],
  },

  {
    id: 523,
    slug: "sp5der-black-basic-hoodie",
    name: "SP5DER Black Basic Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-basic-hoodie.png",
    deals: [],
  },

  {
    id: 524,
    slug: "sp5der-black-basic-sweatpants",
    name: "SP5DER Black Basic Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-basic-sweatpants.png",
    deals: [],
  },

  {
    id: 525,
    slug: "sp5der-black-floral-hoodie",
    name: "SP5DER Black Floral Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-floral-hoodie.png",
    deals: [],
  },

  {
    id: 526,
    slug: "sp5der-black-pink-hoodie",
    name: "SP5DER Black Pink Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-pink-hoodie.png",
    deals: [],
  },

  {
    id: 527,
    slug: "sp5der-black-pink-sweatpants",
    name: "SP5DER Black Pink Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-pink-sweatpants.png",
    deals: [],
  },

  {
    id: 528,
    slug: "sp5der-black-pink-web-hoodie",
    name: "SP5DER Black Pink Web Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-pink-web-hoodie.png",
    deals: [],
  },

  {
    id: 529,
    slug: "sp5der-black-pink-web-sweatpants",
    name: "SP5DER Black Pink Web Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-black-pink-web-sweatpants.png",
    deals: [],
  },

  {
    id: 530,
    slug: "sp5der-blue-floral-shorts",
    name: "SP5DER Blue Floral Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-blue-floral-shorts.png",
    deals: [],
  },

  {
    id: 531,
    slug: "sp5der-burgundy-floral-hoodie",
    name: "SP5DER Burgundy Floral Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-burgundy-floral-hoodie.png",
    deals: [],
  },

  {
    id: 532,
    slug: "sp5der-burgundy-floral-sweatpants",
    name: "SP5DER Burgundy Floral Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-burgundy-floral-sweatpants.png",
    deals: [],
  },

  {
    id: 533,
    slug: "sp5der-charcoal-floral-hoodie",
    name: "SP5DER Charcoal Floral Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-charcoal-floral-hoodie.png",
    deals: [],
  },

  {
    id: 534,
    slug: "sp5der-charcoal-floral-sweatpants",
    name: "SP5DER Charcoal Floral Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-charcoal-floral-sweatpants.png",
    deals: [],
  },

  {
    id: 535,
    slug: "sp5der-grey-floral-hoodie",
    name: "SP5DER Grey Floral Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-floral-hoodie.png",
    deals: [],
  },

  {
    id: 536,
    slug: "sp5der-grey-floral-shorts",
    name: "SP5DER Grey Floral Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-floral-shorts.png",
    deals: [],
  },

  {
    id: 537,
    slug: "sp5der-grey-floral-sweatpants",
    name: "SP5DER Grey Floral Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-floral-sweatpants.png",
    deals: [],
  },

  {
    id: 538,
    slug: "sp5der-grey-green-hoodie",
    name: "SP5DER Grey Green Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-green-hoodie.png",
    deals: [],
  },

  {
    id: 539,
    slug: "sp5der-grey-green-sweatpants",
    name: "SP5DER Grey Green Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-green-sweatpants.png",
    deals: [],
  },

  {
    id: 540,
    slug: "sp5der-grey-stars-hoodie",
    name: "SP5DER Grey Stars Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-stars-hoodie.png",
    deals: [],
  },

  {
    id: 541,
    slug: "sp5der-grey-stars-sweatpants",
    name: "SP5DER Grey Stars Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-grey-stars-sweatpants.png",
    deals: [],
  },

  {
    id: 542,
    slug: "sp5der-lavender-hoodie",
    name: "SP5DER Lavender Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-lavender-hoodie.png",
    deals: [],
  },

  {
    id: 543,
    slug: "sp5der-lavender-sweatpants",
    name: "SP5DER Lavender Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-lavender-sweatpants.png",
    deals: [],
  },

  {
    id: 544,
    slug: "sp5der-light-blue-floral-hoodie",
    name: "SP5DER Light Blue Floral Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-light-blue-floral-hoodie.png",
    deals: [],
  },

  {
    id: 545,
    slug: "sp5der-light-blue-floral-sweatpants",
    name: "SP5DER Light Blue Floral Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-light-blue-floral-sweatpants.png",
    deals: [],
  },

  {
    id: 546,
    slug: "sp5der-light-blue-hoodie",
    name: "SP5DER Light Blue Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-light-blue-hoodie.png",
    deals: [],
  },

  {
    id: 547,
    slug: "sp5der-light-blue-sweatpants",
    name: "SP5DER Light Blue Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-light-blue-sweatpants.png",
    deals: [],
  },

  {
    id: 548,
    slug: "sp5der-pink-floral-shorts",
    name: "SP5DER Pink Floral Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-pink-floral-shorts.png",
    deals: [],
  },

  {
    id: 549,
    slug: "sp5der-pink-hoodie",
    name: "SP5DER Pink Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-pink-hoodie.png",
    deals: [],
  },

  {
    id: 550,
    slug: "sp5der-pink-sweatpants",
    name: "SP5DER Pink Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-pink-sweatpants.png",
    deals: [],
  },

  {
    id: 551,
    slug: "sp5der-purple-sweatpants",
    name: "SP5DER Purple Sweatpants",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-purple-sweatpants.png",
    deals: [],
  },

  {
    id: 552,
    slug: "sp5der-purple-web-hoodie",
    name: "SP5DER Purple Web Hoodie",
    price: 70,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-purple-web-hoodie.png",
    deals: [],
  },

  {
    id: 553,
    slug: "sp5der-red-floral-shorts",
    name: "SP5DER Red Floral Shorts",
    price: 50,
    category: "Clothing",
    image: "/clothing-transparent/sp5der-red-floral-shorts.png",
    deals: [],
  },

  // BAGS

  {
    id: 40,
    slug: "lv-neverfull",
    name: "LV Neverfull",
    price: 0,
    category: "Bags",
    image: "/lv-neverfull.png",
    badge: "BEST SELLER",
    description: "Message for pricing and available options.",
  },

  {
    id: 41,
    slug: "lv-onthego",
    name: "LV OnTheGo",
    price: 0,
    category: "Bags",
    image: "/lv-onthego.png",
    badge: "NEW DROP",
    description: "Message for pricing and available options.",
  },

  {
    id: 42,
    slug: "lv-speedy",
    name: "LV Speedy",
    price: 0,
    category: "Bags",
    image: "/lv-speedy.png",
    badge: "BEST SELLER",
    description: "Message for pricing and available options.",
  },

  {
    id: 43,
    slug: "lv-pochette-metis",
    name: "LV Pochette Metis",
    price: 0,
    category: "Bags",
    image: "/lv-pochette-metis.png",
    badge: "LIMITED STOCK",
    description: "Message for pricing and available options.",
  },

  {
    id: 44,
    slug: "ysl-loulou",
    name: "YSL LouLou",
    price: 0,
    category: "Bags",
    image: "/ysl-loulou.png",
    badge: "BEST SELLER",
    description: "Message for pricing and available options.",
  },

  {
    id: 45,
    slug: "ysl-sunset",
    name: "YSL Sunset",
    price: 0,
    category: "Bags",
    image: "/ysl-sunset.png",
    badge: "NEW DROP",
    description: "Message for pricing and available options.",
  },

  {
    id: 46,
    slug: "chanel-classic-flap",
    name: "Chanel Classic Flap",
    price: 0,
    category: "Bags",
    image: "/chanel-classic-flap.png",
    badge: "LIMITED STOCK",
    description: "Message for pricing and available options.",
  },
];